Feature/homepage template grid rework
AusDTO/dto-design-guide pull request #106
Opened 2016-12-12 21:24 UTC by klepas

Reworks the homepage mostly as per the design.

Some final tweaking left based on feedback from Gaz.

2016-12-12 21:51 UTC, dominikwilkowski requested changes
Have a look at the svg inlining and we should be good

2016-12-12 21:51 UTC, dominikwilkowski commented on _assets/scss/design-guide.scss
> +    background-image: url('/assets/hero.svg');
Can we inline the SVG to save that precious http request (prior to http/2 rollout)?
E.G.:
```css
url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1000' height='20' version='1.1'><polyline fill='white' points='0,0 1000,0 0,20'/></svg>") left top / 100% auto no-repeat
```

http://meyerweb.com/eric/tools/dencoder/

2016-12-12 21:51 UTC, dominikwilkowski commented on _assets/scss/design-guide.scss
> +.no-svg {
Just a question but should be include the `no-svg` class as a default on our html tag? That way we have a fallback when js is off?

2016-12-12 21:51 UTC, dominikwilkowski commented on _assets/scss/design-guide.scss
> +
nice comments :)

2016-12-12 21:51 UTC, dominikwilkowski commented on _assets/scss/design-guide.scss
> +          & > h2 {
some deep nesting here..

2016-12-12 21:51 UTC, dominikwilkowski commented on _config.yml
>      order: 0
Do we actually need this in the config? I mean do we reuse it anywhere else?

2016-12-12 22:21 UTC, dominikwilkowski commented
In fact use this string for the background image @klepas 

```css
background-image: url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20viewBox%3D%220%200%20600%20295%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cpath%20fill%3D%22%2329C1E3%22%20d%3D%22M74%2019h318v208H74z%22/%3E%3Cpath%20fill%3D%22%23244A61%22%20d%3D%22M392%20226H77V19h315v207zM234.996%206A3.002%203.002%200%200%201%20238%209a2.999%202.999%200%201%201-6%200c0-1.656%201.34-3%202.996-3zm171.616-6H63.388C61.525%200%2060%201.717%2060%203.815v236.637c0%202.098%201.525%203.815%203.388%203.815h157.614c-.015.03-.042.057-.056.088l-9.593%2021.91c-.41.94-1.47%201.985-2.353%202.32l-17.855%206.803c-.882.337-.842.612.09.612h87.527c.933%200%20.974-.275.09-.612L261%20268.586c-.883-.336-1.942-1.38-2.355-2.322l-9.595-21.91c-.013-.03-.04-.056-.054-.087h157.616c1.863%200%203.388-1.717%203.388-3.815V3.815C410%201.717%20408.475%200%20406.612%200zM60%200h136%22/%3E%3Cpath%20fill%3D%22%234597B9%22%20d%3D%22M85%2026h301v30H85z%22/%3E%3Cpath%20fill%3D%22%2397E4F2%22%20d%3D%22M85%2062h41v163H85zm50%2088h252v76H135zm0-47h79v41h-79zm85%200h79v41h-79zm86%200h79v41h-79zM144.133%2077.854h7.168v9.367c-1.16.38-2.255.646-3.28.8-1.026.15-2.075.227-3.146.227-2.727%200-4.81-.8-6.247-2.404-1.438-1.602-2.156-3.903-2.156-6.902%200-2.915.835-5.19%202.503-6.82%201.67-1.632%203.982-2.447%206.94-2.447%201.853%200%203.64.37%205.363%201.112l-1.273%203.065a9.08%209.08%200%200%200-4.115-.99c-1.656%200-2.983.557-3.98%201.67-.997%201.112-1.495%202.607-1.495%204.485%200%201.96.402%203.46%201.205%204.493.803%201.034%201.97%201.55%203.503%201.55.8%200%201.612-.082%202.436-.246v-3.77h-3.423v-3.188zm14.212-7.922l.173.272c-.412%201.623-1.137%203.596-2.175%205.92h-2.707c.57-2.44.98-4.503%201.236-6.192h3.473zm6.822%2018.315c-1.623%200-2.898-.63-3.825-1.89-.927-1.26-1.39-3.008-1.39-5.24%200-2.266.47-4.03%201.414-5.296.944-1.264%202.244-1.896%203.9-1.896%201.738%200%203.064.675%203.98%202.027h.123c-.19-1.03-.286-1.948-.286-2.755V68.77h3.782V88h-2.892l-.73-1.792h-.16c-.857%201.36-2.162%202.04-3.917%202.04zm1.322-3.003c.963%200%201.67-.28%202.118-.84.45-.56.695-1.512.736-2.855v-.41c0-1.482-.23-2.545-.686-3.187-.457-.643-1.2-.964-2.23-.964-.84%200-1.494.355-1.96%201.068-.465.712-.698%201.748-.698%203.108s.235%202.38.705%203.06c.47.678%201.14%201.018%202.014%201.018zM185.582%2088l-.73-1.878h-.098c-.635.8-1.288%201.353-1.96%201.662-.67.31-1.546.463-2.625.463-1.327%200-2.37-.38-3.133-1.137-.762-.758-1.143-1.837-1.143-3.238%200-1.466.513-2.548%201.538-3.244%201.026-.696%202.573-1.08%204.64-1.155l2.398-.074v-.607c0-1.4-.716-2.1-2.15-2.1-1.104%200-2.402.333-3.893%201l-1.248-2.546c1.59-.832%203.352-1.248%205.288-1.248%201.854%200%203.275.403%204.264%201.21.99.808%201.483%202.035%201.483%203.683V88h-2.632zm-1.113-6.402l-1.458.05c-1.096.033-1.91.23-2.447.593-.535.364-.803.916-.803%201.657%200%201.063.61%201.594%201.83%201.594.872%200%201.57-.25%202.094-.753.523-.502.784-1.17.784-2.002V81.6zm5.648-7.415h4.128l2.607%207.774c.223.675.375%201.475.458%202.397h.075c.09-.848.268-1.647.53-2.397l2.56-7.774h4.04l-5.845%2015.584c-.535%201.442-1.3%202.52-2.292%203.238-.993.717-2.153%201.075-3.48%201.075-.65%200-1.29-.07-1.915-.21v-2.99c.453.107.948.16%201.483.16.668%200%201.25-.204%201.75-.612.497-.407.887-1.023%201.167-1.847l.222-.68-5.487-13.717zm20.07%2011.16c-.428%201.664-1.153%203.637-2.175%205.92h-2.72c.537-2.192.953-4.26%201.25-6.204h3.46l.185.283zM231.766%2088l-1.063-4.832-1.434-6.105h-.087L226.663%2088h-4.055l-3.93-13.817h3.757l1.594%206.118c.255%201.097.514%202.608.778%204.536h.074c.033-.626.177-1.62.433-2.978l.197-1.05%201.706-6.625h4.152l1.62%206.624c.032.182.084.45.154.804.07.355.138.732.204%201.132.065.4.125.79.18%201.174.052.383.083.69.09.92h.076c.074-.593.206-1.407.395-2.44.19-1.034.325-1.733.407-2.095l1.656-6.117h3.695L235.868%2088h-4.102zm13.31-6.933c0%201.368.224%202.402.673%203.102.448.7%201.18%201.05%202.193%201.05%201.005%200%201.728-.35%202.17-1.045.44-.696.66-1.732.66-3.108%200-1.368-.223-2.393-.668-3.077-.444-.684-1.174-1.026-2.187-1.026-1.005%200-1.73.34-2.175%201.02-.445.68-.667%201.707-.667%203.083zm9.553%200c0%202.25-.595%204.008-1.78%205.277-1.187%201.27-2.84%201.903-4.957%201.903-1.326%200-2.496-.29-3.51-.87-1.013-.582-1.79-1.416-2.335-2.504-.544-1.087-.816-2.356-.816-3.806%200-2.257.59-4.012%201.767-5.265%201.178-1.252%202.834-1.878%204.967-1.878%201.327%200%202.497.288%203.51.865%201.014.576%201.792%201.404%202.336%202.483.544%201.08.816%202.344.816%203.794zm10.825-7.143c.51%200%20.935.037%201.272.11l-.284%203.536a4.287%204.287%200%200%200-1.112-.124c-1.202%200-2.14.31-2.81.927-.672.618-1.008%201.483-1.008%202.595V88h-3.77V74.183h2.856l.556%202.324h.185a5.174%205.174%200%200%201%201.736-1.873%204.29%204.29%200%200%201%202.38-.71zM273.005%2088h-3.77V68.77h3.77V88zm8.33.247c-1.623%200-2.898-.63-3.825-1.89-.927-1.26-1.39-3.008-1.39-5.24%200-2.266.47-4.03%201.415-5.296.943-1.264%202.243-1.896%203.9-1.896%201.737%200%203.064.675%203.978%202.027h.124c-.19-1.03-.284-1.948-.284-2.755V68.77h3.78V88h-2.89l-.73-1.792h-.16c-.857%201.36-2.163%202.04-3.918%202.04zm1.322-3.003c.964%200%201.67-.28%202.12-.84.45-.56.694-1.512.735-2.855v-.41c0-1.482-.23-2.545-.686-3.187-.457-.643-1.2-.964-2.23-.964-.84%200-1.494.355-1.96%201.068-.465.712-.698%201.748-.698%203.108s.235%202.38.705%203.06c.47.678%201.14%201.018%202.014%201.018zm9.788.99c0-.693.185-1.216.556-1.57.372-.355.912-.532%201.62-.532.684%200%201.213.18%201.588.544.375.362.563.88.563%201.557%200%20.65-.19%201.163-.568%201.538-.38.376-.906.564-1.582.564-.692%200-1.227-.184-1.606-.55-.38-.367-.57-.884-.57-1.55zM306%2065h79v4h-79zm0%207h79v4h-79zm0%207h79v4h-79zm0%207h79v4h-79zm0%207h53v4h-53z%22/%3E%3Cpath%20fill%3D%22%23244A61%22%20d%3D%22M468%20278h126.574c1.884%200%203.426%201.723%203.426%203.828v7.344c0%202.105-1.542%203.828-3.426%203.828H288.426c-1.884%200-3.426-1.723-3.426-3.828v-7.344c0-2.105%201.542-3.828%203.426-3.828H416v4.055c0%201.07.772%201.945%201.715%201.945h48.57c.943%200%201.715-.875%201.715-1.945V278zm86-17.948c0%201.07-.77%201.948-1.71%201.948H329.71c-.94%200-1.71-.877-1.71-1.948V114.948c0-1.07.77-1.948%201.71-1.948h222.58c.94%200%201.71.877%201.71%201.948v145.104zM441.497%20106c.826%200%201.503.67%201.503%201.503%200%20.828-.677%201.497-1.503%201.497-.828%200-1.497-.67-1.497-1.497%200-.832.67-1.503%201.497-1.503zm-122.787-4c-.94%200-1.71.878-1.71%201.95v168.1c0%201.072.77%201.95%201.71%201.95h244.58c.94%200%201.71-.878%201.71-1.95v-168.1c0-1.072-.77-1.95-1.71-1.95H318.71z%22/%3E%3Cpath%20fill%3D%22%2329C1E3%22%20d%3D%22M328%20113h227v151H328z%22/%3E%3Cpath%20fill%3D%22%2397E4F2%22%20d%3D%22M349.103%20143.11h5.575v7.284c-.903.295-1.754.502-2.552.62-.798.12-1.613.178-2.446.178-2.12%200-3.74-.623-4.86-1.87-1.117-1.246-1.676-3.035-1.676-5.368%200-2.268.65-4.037%201.946-5.305%201.298-1.27%203.097-1.905%205.397-1.905%201.442%200%202.833.29%204.172.865l-.99%202.384a7.086%207.086%200%200%200-3.202-.77c-1.288%200-2.32.434-3.095%201.3-.775.864-1.163%202.027-1.163%203.488%200%201.525.312%202.69.937%203.494.625.804%201.533%201.206%202.725%201.206.622%200%201.253-.064%201.894-.192v-2.932h-2.663v-2.48zm11.054-6.163l.135.212c-.32%201.26-.885%202.796-1.692%204.603h-2.105c.442-1.897.763-3.502.96-4.816h2.702zm5.306%2014.245c-1.262%200-2.254-.49-2.975-1.47-.72-.98-1.08-2.34-1.08-4.076%200-1.762.366-3.135%201.1-4.12.733-.982%201.744-1.474%203.032-1.474%201.352%200%202.384.525%203.095%201.576h.096a12.09%2012.09%200%200%201-.22-2.143v-3.44h2.94V151h-2.248l-.567-1.394h-.125c-.666%201.058-1.682%201.586-3.047%201.586zm1.028-2.335c.75%200%201.3-.218%201.65-.654.35-.436.54-1.176.572-2.22v-.318c0-1.153-.178-1.98-.534-2.48-.355-.5-.934-.75-1.735-.75-.653%200-1.16.278-1.523.832-.362.554-.543%201.36-.543%202.418%200%201.057.182%201.85.548%202.38.365.527.887.792%201.566.792zM381.343%20151l-.567-1.46h-.077c-.493.62-1%201.05-1.523%201.292-.523.24-1.204.36-2.043.36-1.032%200-1.844-.295-2.437-.884-.592-.59-.89-1.43-.89-2.518%200-1.14.4-1.982%201.198-2.524. [...]

2016-12-12 23:10 UTC, klepas commented on _assets/scss/design-guide.scss
> +.no-svg {
Good thinking… should I add it directly to the `<html>`?

2016-12-12 23:11 UTC, dominikwilkowski commented on _assets/scss/design-guide.scss
> +.no-svg {
I would

2016-12-13 01:58 UTC, klepas commented on _assets/scss/design-guide.scss
> +.no-svg {
Noting this is resolved b/c modernizr’s behaviour has changed slightly.

2016-12-13 01:59 UTC, dominikwilkowski approved these changes

2016-12-13 02:06 UTC, merged