This Feature/content refactor pascals qa
AusDTO/dto-design-guide pull request #44
Opened 2016-11-29 06:05 UTC by klepas

This PR holds things. I will figure out what they are momentarily >_<

2016-11-29 06:09 UTC, dominikwilkowski approved these changes

2016-11-29 06:17 UTC, klepas commented
@joolswood Hey, I just wanna get your blessing re. the minor content edits — could you take a quick squiz at the diffs of the MD files? (:

2016-11-29 09:05 UTC, klepas commented
Added:

- breadcrumbs! (currently just set to support a tier-2 IA, and usage of Jekyll Collections)
- breadcrumb style: inverted, and set to $darker-aqua — think it looks better than `$non-white` (the default) — what do y’all think? :)
- scss source URL bugfix
- changes the beta badge in the header to maroon, as set by the `badge--beta` styling

2016-11-30 02:38 UTC, dominikwilkowski commented
The breadcrumbs have a bug where the "overview" page link goes nowhere. Let me see if I can find the code responsible

2016-11-30 02:38 UTC, dominikwilkowski requested changes
Breadcrumb bug

2016-11-30 03:27 UTC, dominikwilkowski requested changes
The `overview` bug

2016-11-30 03:27 UTC, dominikwilkowski commented on _includes/header.liquid
> +        </a></li>
some indentation funkiness?

2016-11-30 03:27 UTC, dominikwilkowski commented on _includes/header.liquid
> +            {% if page_title_slugified == page.parent %}
We could either do:
```liquid
<li>
  {% if page_title_slugified == page.parent %}
    <a href="/{{ page.parent }}/index.html">
      Overview
    </a>
  {% else %}
    <a href="/{{ page.parent }}/{{ page_title_slugified }}">
      {{ page.title }}
    </a>
  {% endif %}
</li>
```

or not link to the last link as that's always going to be the page we are currently on...

```liquid
<li>
  {% if page_title_slugified == page.parent %}
    Overview
  {% else %}
    {{ page.title }}
  {% endif %}
</li>
```

2016-11-30 04:12 UTC, gazhands commented
Cheers for the update!
Think we could go with default breadcrumb style ;)

2016-11-30 23:06 UTC, dominikwilkowski approved these changes

2016-11-30 23:06 UTC, dominikwilkowski commented on _includes/header.liquid
> +      for its page.parent.
nice catch

2016-11-30 23:06 UTC, dominikwilkowski commented on _includes/header.liquid
> +          {% if page_title_slugified == page.parent %}
So we're going with the link for the last bit, cool

2016-11-30 23:06 UTC, dominikwilkowski commented on _includes/header.liquid
> +        <a href="/" class="logo">{{ site.title }}
I personally make it easy for me to catch those things by indenting all levels unless you only have a string you wrap in a tag.

```html
<a href="/" class="logo">
	{{ site.title }}
	<span class="uikit--version">{% uikit_version %}</span>
</a>
```

But no need to change this... :)

2016-12-01 00:58 UTC, merged